creacion de modelo de reviews y sus relaciones
gonza-fl/e-comerce-joyeria pull request #161
Opened 2021-06-23 15:42 UTC by jaimegalvis

2021-06-23 15:45 UTC, scriptnoob12 requested changes
El modelo esta bien, pero la calificación se basa en un sistema de 5 estrellas. Tendrías que adaptarla para que pueda implementarse este sistema.

2021-06-23 16:07 UTC, scriptnoob12 approved these changes

2021-06-24 02:03 UTC, RJurado16 requested changes

2021-06-24 02:03 UTC, RJurado16 commented on api/src/models/index.js
> +Product.hasMany(Review);
Faltó el Review.belongsTo(Product);

y abajo después de Review.belongsTo(User);
falta el User.hasMany(Review);

2021-06-24 02:06 UTC, RJurado16 commented on api/src/controllers/product.js
> +      include: [Category, Image, Review],
Muy bueno esto, no lo sabía

2021-06-24 02:09 UTC, RJurado16 commented on api/src/routes/review.js
> +  mergeParams: true,
No entendí esto, por más de que esté comentado, no lo usé nunca y no sé para qué sirve o cuál es el objetivo. Me explicarías? quisiera aprenderlo

2021-06-24 02:38 UTC, RJurado16 commented on api/src/controllers/review.js
> +    const response = await Product.findOne({
Así llega un objeto product con dentro un atributo reviews que es un array de reviews. Al ser una relación uno-muchos, el muchos (modelo review) genera automáticamente un campo 'productId' que apunta al producto.
Así como está entonces tenés { reviews: [ {id: 1, descripcion: "", productId: 3}, {id: 2, descripcion: "", productId: 3}, ... ]}

Al front quizá le conviene que llegue un array de objetos reviews, todos sobre el mismo producto.
entonces hacer algo como response = await Review.findAll({ where: { productId: idProduct } })
Daría entonces algo como [ {id: 1, descripcion: "", productId: 3}, {id: 2, descripcion: "", productId: 3}, ... ]
Se reduce un nivel de profundidad (el objeto producto) porque es innecesario ya que toda review tiene para buscar el mismo id del producto

2021-06-24 02:41 UTC, RJurado16 commented on api/src/models/Reviews.js
> +    timestamps: false,
El front necesita mostrar la fecha de la review. Creo que si quitabas el { timestamps: false } se generaban dos atributos nuevos, 'createdAt' y 'updatedAt'. Al front le va a servir el 'updatedAt' para tener la fecha de publicación de la review (y luego si quiere modificar la review, se actualiza el mismo atributo y sigue mostrando el updatedAt)

2021-06-24 03:56 UTC, jaimegalvis commented on api/src/routes/review.js
> +  mergeParams: true,
Como estoy enrutando desde el archivo /routes/product.js así => router.use('/:idProduct/review', review);
Entonces cuando hago la ruta get en este archívo no le estoy pasando el :idProduct si no que está en la ruta "padre" de products entonces el mergeParams permite que llegue el idProduct desde ese archivo padre. Si no se pone, al no poner el :idProduct en la ruta pues nunca la va a leer por parametros

2021-06-24 04:12 UTC, jaimegalvis commented on api/src/models/index.js
> +Product.hasMany(Review);
No se que tan necesario sea el Review.belongsTo(Product) si no vamos a necesitar los datos del Review desde producto si no que todo lo manejamos en el Review directamente

2021-06-24 05:19 UTC, jaimegalvis commented on api/src/models/Reviews.js
> +    timestamps: false,
Al quitar esto no me corre la tabla. Si me pueden dar una mano con este error estaría bueno

2021-06-24 19:04 UTC, RJurado16 approved these changes

2021-06-24 19:04 UTC, merged