Fix (api/controllers) added new restrictions
gonza-fl/e-comerce-joyeria pull request #162
Opened 2021-06-23 16:06 UTC by scriptnoob12

* Ahora al actualizar un producto y se deja vacío el campo, este no se modifica.

2021-06-23 18:36 UTC, jaimegalvis requested changes
falta mirar como updetear las imagenes, porque llegan el arreglo que traia antes y pueden que cambie solo un parametro que quedaria [{id....},{id....}, 'dataParaCloud']

2021-06-24 00:47 UTC, scriptnoob12 commented
> falta mirar como updetear las imagenes, porque llegan el arreglo que traia antes y pueden que cambie solo un parametro que quedaria [{id....},{id....}, 'dataParaCloud']

Cuando se apruebe esta, lo subo en otra rama.

2021-06-24 19:17 UTC, RJurado16 approved these changes

2021-06-25 03:07 UTC, jaimegalvis approved these changes

2021-06-25 03:24 UTC, merged